version: '3.8'

services:
  starbound:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starbound
    ports:
      - "21025:21025"
      - "28015:28015"
      - "28016:28016"
    volumes:
      - ../starbound_data:/starbound
    restart: unless-stopped
    stdin_open: true
    tty: true


